require_relative 'sinqia_module'
require_relative 'sinqia_bank'
require_relative 'sinqia_account'
require_relative 'sinqia_individual'
require_relative 'sinqia_transfer'
require_relative 'sinqia_service'
require_relative 'sinqia_documents'
